name: Start Railway DB manually

on:
  workflow_dispatch:  

jobs:
  start-db:
    runs-on: ubuntu-latest
    steps:
      - name: Start Railway DB
        run: |
            curl --request POST \
            --url https://backboard.railway.com/graphql/v2 \
            --header 'Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{"query":"query { me { name email } }"}'\
        
